GHA combine all tox jobs under a single build matrix (#2754)

diff --git a/.github/workflows/tox.yml b/.github/workflows/tox.yml
--- a/.github/workflows/tox.yml
+++ b/.github/workflows/tox.yml
@@ -25,82 +25,11 @@ concurrency:
 env:
   FORCE_COLOR: 1 # tox, pytest, ansible-lint
   PY_COLORS: 1
-  TOX_PARALLEL_NO_SPINNER: 1
 
 jobs:
-  linters:
-    name: >-
-      ${{ matrix.env.TOXENV }}
-    runs-on: ${{ matrix.os }}
-    strategy:
-      fail-fast: false
-      matrix:
-        python-version:
-          - 3.9
-        os:
-          - ubuntu-20.04
-        env:
-          - TOXENV: lint
-          - TOXENV: docs
-          - TOXENV: eco
-          - TOXENV: packaging
-          - TOXENV: validate-hook
-
-    steps:
-      - name: Check out src from Git
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0 # needed by setuptools-scm
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v4
-        with:
-          python-version: ${{ matrix.python-version }}
-          cache: "pip"
-      # - name: set PY_SHA256
-      #   run: echo "::set-env name=PY_SHA256::$(python -VV | sha256sum | cut -d' ' -f1)"
-      # - name: Pre-commit cache
-      #   uses: actions/cache@v1
-      #   with:
-      #     path: ~/.cache/pre-commit
-      #     key: ${{ runner.os }}-pre-commit-${{ env.PY_SHA256 }}-${{ hashFiles('setup.cfg') }}-${{ hashFiles('tox.ini') }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('.pre-commit-config.yaml') }}-${{ hashFiles('pytest.ini') }}
-      # - name: Pip cache
-      #   uses: actions/cache@v1
-      #   with:
-      #     path: ~/.cache/pip
-      #     key: ${{ runner.os }}-pip-${{ env.PY_SHA256 }}-${{ hashFiles('setup.cfg') }}-${{ hashFiles('tox.ini') }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('.pre-commit-config.yaml') }}-${{ hashFiles('pytest.ini') }}
-      #     restore-keys: |
-      #       ${{ runner.os }}-pip-
-      #       ${{ runner.os }}-
-      - name: Install tox
-        run: |
-          python3 -m pip install --upgrade pip
-          python3 -m pip install --upgrade tox
-      - name: Log installed dists
-        run: >-
-          python -m pip freeze --all
-      - name: Initialize tox envs
-        run: >-
-          python -m
-          tox
-          --parallel auto
-          --parallel-live
-          --notest
-          --skip-missing-interpreters false
-          -vv
-        env: ${{ matrix.env }}
-      - name: Test with tox
-        run: |
-          python -m tox --parallel auto --parallel-live
-        env: ${{ matrix.env }}
-      - name: Archive logs
-        uses: actions/upload-artifact@v3
-        with:
-          name: logs.zip
-          path: .tox/**/log/
-
-  unit:
+  build:
     name: ${{ matrix.name || matrix.tox_env }}
-    runs-on: ${{ matrix.os }}
+    runs-on: ${{ matrix.os || 'ubuntu-22.04' }}
     defaults:
       run:
         shell: ${{ matrix.shell || 'bash'}}
@@ -113,20 +42,13 @@ jobs:
       # proof that we failed to catch a bug by not running it. Using
       # distribution should be preferred instead of custom builds.
       matrix:
-        name:
-          - py38
-        tox_env:
-          - py38
-        python-version:
-          - 3.8
-        os:
-          # https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
-          - ubuntu-20.04
-        # - windows-latest
-        # - windows-2016
+        # https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
         include:
           # keep list sorted as it determines UI order too
           # linux
+          - tox_env: lint
+          - tox_env: pkg,hook,docs
+          - tox_env: eco # slow, keep separated
           # py38 is first and comes from matrix
           - tox_env: py38 # no devel for 3.8 as core dropped support for it
             os: ubuntu-20.04
@@ -189,12 +111,12 @@ jobs:
             ~/.ansible/roles/
           key: galaxy-${{ matrix.name }}-${{ hashFiles('requirements.yml') }}
 
-      - name: Set up Python ${{ matrix.python-version }}
+      - name: Set up Python ${{ matrix.python-version || '3.9' }}
         if: "!contains(matrix.shell, 'wsl')"
         uses: actions/setup-python@v4
         with:
           cache: pip
-          python-version: ${{ matrix.python-version }}
+          python-version: ${{ matrix.python-version || '3.9' }}
 
       - name: Run ./tools/test-setup.sh
         run: ./tools/test-setup.sh
@@ -202,7 +124,7 @@ jobs:
       - name: Install tox
         run: |
           python3 -m pip install --upgrade pip
-          python3 -m pip install --upgrade tox tox-extra
+          python3 -m pip install --upgrade "tox>=4.0.0rc1"
 
       - name: Log installed dists
         run: python3 -m pip freeze --all
@@ -212,15 +134,16 @@ jobs:
         timeout-minutes: 5 # average is under 1, but macos can be over 3
 
       # sequential run improves browsing experience (almost no speed impact)
-      - name: "Test with tox: ${{ matrix.tox_env }}"
+      - name: tox -e ${{ matrix.tox_env }}
         run: python3 -m tox -e ${{ matrix.tox_env }}
 
       - name: Combine coverage data
+        if: "(matrix.cover || false) && runner.os == 'Linux'"
         # produce a single .coverage file at repo root
         run: tox -e coverage
 
       - name: Upload coverage data
-        if: "runner.os == 'Linux'"
+        if: "(matrix.cover || false) && runner.os == 'Linux'"
         uses: codecov/codecov-action@v3
         with:
           name: ${{ matrix.tox_env }}
@@ -241,7 +164,53 @@ jobs:
         uses: shyim/junit-report-annotations-action@3d2e5374f2b13e70f6f3209a21adfdbc42c466ae
         with:
           path: .tox/junit.*.xml
-        if: always()
+        if: always() && (matrix.cover || false)
+
+      - name: Report failure if git reports dirty status
+        run: |
+          if [[ -n $(git status -s) ]]; then
+            # shellcheck disable=SC2016
+            echo -n '::error file=git-status::'
+            printf '### Failed as git reported modified and/or untracked files\n```\n%s\n```\n' "$(git status -s)" | tee -a "$GITHUB_STEP_SUMMARY"
+            exit 99
+          fi
+        # https://github.com/actions/toolkit/issues/193
+  codeql:
+    name: codeql
+    runs-on: ubuntu-latest
+    permissions:
+      actions: read
+      contents: read
+      security-events: write
+
+    strategy:
+      fail-fast: false
+      matrix:
+        language: ["python"]
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
+
+      # Initializes the CodeQL tools for scanning.
+      - name: Initialize CodeQL
+        uses: github/codeql-action/init@v2
+        with:
+          languages: ${{ matrix.language }}
+          # If you wish to specify custom queries, you can do so here or in a config file.
+          # By default, queries listed here will override any specified in a config file.
+          # Prefix the list here with "+" to use these queries and those in the config file.
+
+          # Details on CodeQL's query packs refer to : https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
+          # queries: security-extended,security-and-quality
+
+      - name: Autobuild
+        uses: github/codeql-action/autobuild@v2
+
+      - name: Perform CodeQL Analysis
+        uses: github/codeql-action/analyze@v2
+        with:
+          category: "/language:${{matrix.language}}"
 
   check: # This job does nothing and is only used for the branch protection
     if: always()
@@ -249,8 +218,7 @@ jobs:
       pull-requests: write # allow codenotify to comment on pull-request
 
     needs:
-      - linters
-      - unit
+      - build
 
     runs-on: ubuntu-latest
 
